spring:
  application:
    name: service-provider-dockerfilemavenplugin
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.99.100:8848
#  cloud:
#    zookeeper:
#      connect-string: 192.168.99.100:2181
#      discovery:
#        enabled: true
server:
    port: 8092
