FROM java:8
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/nginx
VOLUME /nginx 
# 将jar包添加到容器中并更名为app.jar
ADD service-provider-0.0.1-SNAPSHOT.jar app.jar 
# 运行jar包
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
